CREATE PROC FI_SP_IncBeneficiario

		@CEP VARCHAR(max),
		@CPF VARCHAR(14),
		@IdCliente BIGINT
        
AS
BEGIN
	INSERT INTO BENBENEFICIARIOS(CEP, CPF, IDCLIENTE) 
	VALUES (@CEP, @CPF, @IdCliente)

	SELECT SCOPE_IDENTITY()
END